### ISSUE TITLE
better explained GUI

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Mattomanx77/tmodloader-crescent#2]
I'm 90% sure that i just deleted all my skill points because the GUI is just horribly designed.

Just having text when you hover over an button to know what it does (or in case on stats what they will effect) would help a lot to see what the hell is going on

**Comment by Mattomanx77** [comment]
I'd appreciate a less angry response, but yes I have considered adding tool
tips. I don't have great knowledge on how to add them but I have that exact
thing written down for next update.
